/**
 * Every scene of every tour, generated by `npm run scenes` from the Lesco
 * Viewer. Companion to `src/hero/tours.ts`, which carries one frame per tour
 * for the hero.
 *
 * Kept apart from that manifest on purpose. This one is thirty scenes deep and
 * carries a placeholder for each; the hero needs its own metadata on the first
 * frame, and dragging this along would put ~10KB of data URIs into the initial
 * chunk for a page most visitors scroll rather than enter. Nothing here is
 * imported until someone opens a tour.
 */

import data from './scenes.json';
import { asset } from '../hero/tours';

export interface Hotspot {
  id: string;
  /** Viewer convention: radians. Where the doorway sits in this scene. */
  yaw: number;
  pitch: number;
  /** Scene id this hotspot walks into. */
  destino: string;
  /** The viewer's own arrow hint — 'cima-direita' and friends, or null. */
  direcao: string | null;
}

export interface Scene {
  id: string;
  nome: string;
  /** Where the scene opens. Radians for yaw and pitch, degrees of vertical fov. */
  vista: { yaw: number; pitch: number; fov: number };
  hotspots: Hotspot[];
  /** 4096-wide equirectangular panorama. */
  src: string;
  /** 2048-wide, for narrow viewports and Save-Data. */
  srcSmall: string;
  /** Reprojected still for the scene strip. */
  thumb: string;
  /** A few hundred bytes of blur, shown while the panorama downloads. */
  lqip: string;
}

export interface TourScenes {
  slug: string;
  obra: string;
  cidade: string;
  uf: string;
  escritorio: string | null;
  /** Scene the tour opens at — the one the gallery card and the hero show. */
  capa: string;
  cenas: Scene[];
}

/** Paths are absolute in the manifest; rebase them onto the deployed base. */
export const TOUR_SCENES: TourScenes[] = (data as unknown as TourScenes[]).map(
  (tour) => ({
    ...tour,
    cenas: tour.cenas.map((scene) => ({
      ...scene,
      src: asset(scene.src),
      srcSmall: asset(scene.srcSmall),
      thumb: asset(scene.thumb),
    })),
  }),
);

export const findTour = (slug: string): TourScenes | null =>
  TOUR_SCENES.find((tour) => tour.slug === slug) ?? null;

/** "São Paulo/SP · Setin" — the same line the hero's reel shows. */
export function place(tour: TourScenes): string {
  const city = `${tour.cidade}/${tour.uf}`;
  return tour.escritorio ? `${city} · ${tour.escritorio}` : city;
}
