/**
 * The tour manifest, generated by `npm run tours` from the Lesco Viewer.
 *
 * Kept apart from panorama.ts on purpose: the hero's caption and slideshow
 * indicator need this metadata immediately, while three.js only loads once we
 * know the viewport can use it. Importing the manifest from the scene module
 * would drag the whole renderer into the initial chunk.
 */

import data from './tours.json';

export interface Tour {
  slug: string;
  obra: string;
  cidade: string;
  uf: string;
  tipo: string;
  ano: number;
  escritorio: string | null;
  /** Name of the cover scene, as titled in the viewer. */
  cena: string;
  /** How many scenes the full tour has. */
  cenas: number;
  /** Viewer convention: radians for yaw and pitch, degrees of vertical fov. */
  vista: { yaw: number; pitch: number; fov: number };
  src: string;
  srcSmall: string;
  /**
   * Mean luminance of the horizon band, 0-255, measured at build time. Purely
   * informational: the tours are shown at their true brightness, so this is
   * here for whoever tunes the scrim, not applied as a correction.
   */
  luma: number;
  /**
   * Published tour URL. Absent until tours.lesco.com.br goes live, and the
   * gallery card stays unlinked while it is.
   */
  url?: string;
  /** A few hundred bytes of blur, shown while the panorama downloads. */
  lqip: string;
}

/**
 * Rebase a manifest path onto wherever the site is actually served from.
 *
 * The generator writes these absolute (`/tours/foo.webp`), which is where they
 * sit in public/. Vite rewrites that kind of path in index.html and in CSS, but
 * not these: they arrive as JSON data and go straight to the texture loader, so
 * there is no import for the build to rewrite. Hence doing it by hand, against
 * the one value Vite does expose — '/' in dev, the configured base in a build.
 */
export const asset = (path: string): string =>
  `${import.meta.env.BASE_URL}${path.replace(/^\//, '')}`;

export const TOURS: Tour[] = (data as unknown as Tour[]).map((tour) => ({
  ...tour,
  src: asset(tour.src),
  srcSmall: asset(tour.srcSmall),
}));

/** "São Paulo/SP · Setin" — city, state, and the client who commissioned it. */
export function describe(tour: Tour): string {
  const place = `${tour.cidade}/${tour.uf}`;
  return tour.escritorio ? `${place} · ${tour.escritorio}` : place;
}
